### ISSUE TITLE
Repository is in Breach of MIT License

### ISSUE THREAD

**Issue by MarkBaker** [YoloZoloo/PhpSpreadSheet#1]
This repository is in breach of the terms of the PhpSpreadsheet MIT License:

> Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

**Comment by YoloZoloo** [comment]
Thanks for letting me know.
Closed by 2a940159aa5f1f8727d2f9f90ae606e870270f49.

**Comment by YoloZoloo** [comment]
Sorry. Fix wasn't correct. Re-fixed on c92e3ff
