### ISSUE TITLE
Cannot Read Excel Files

### ISSUE THREAD

**Issue by VidurK2** [YoloZoloo/PhpSpreadSheet#2]
There is some issue while trying to read excel files. Here is the issue that I encountered.

`
Warning: The use statement with non-compound name 'ZipArchive' has no effect in C:\xampp\htdocs\AnyFolder\PhpOffice\autoload.php on line 3

Warning: include(C:\xampp\htdocs\AnyFolder\ZipArchive.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\AnyFolder\PhpOffice\autoload.php on line 8

Warning: include(): Failed opening 'C:\xampp\htdocs\AnyFolder\ZipArchive.php' for inclusion (include_path='\xampp\php\PEAR') in C:\xampp\htdocs\AnyFolder\PhpOffice\autoload.php on line 8

Fatal error: Uncaught Error: Class "ZipArchive" not found in C:\xampp\htdocs\AnyFolder\PhpOffice\PhpSpreadsheet\Shared\File.php:63 Stack trace: #0 C:\xampp\htdocs\AnyFolder\PhpOffice\PhpSpreadsheet\Shared\File.php(179): PhpOffice\PhpSpreadsheet\Shared\File::fileExists('zip://C:\\xampp\\...') #1 C:\xampp\htdocs\AnyFolder\PhpOffice\PhpSpreadsheet\Reader\Xlsx.php(80): PhpOffice\PhpSpreadsheet\Shared\File::testFileNoThrow('C:\\xampp\\htdocs...', '_rels/.rels') #2 C:\xampp\htdocs\AnyFolder\PhpOffice\PhpSpreadsheet\IOFactory.php(123): PhpOffice\PhpSpreadsheet\Reader\Xlsx->canRead('C:\\xampp\\htdocs...') #3 C:\xampp\htdocs\AnyFolder\PhpOffice\PhpSpreadsheet\IOFactory.php(84): PhpOffice\PhpSpreadsheet\IOFactory::createReaderForFile('C:\\xampp\\htdocs...') #4 C:\xampp\htdocs\AnyFolder\PhpOffice\test.php(12): PhpOffice\PhpSpreadsheet\IOFactory::load('C:\\xampp\\htdocs...') #5 {main} thrown in C:\xampp\htdocs\AnyFolder\PhpOffice\PhpSpreadsheet\Shared\File.php on line 63`

Do advise how to fix this. Thanks

**Comment by YoloZoloo** [comment]
Thanks for reporting this. I am aware that this repo needs to include some of the needed files. 
For now, I can't guarantee any ETA on the fix. But I will take a look at this when the time allows.

**Comment by YoloZoloo** [comment]
@VidurK2 to keep you in loop, I couldn't allocate time to work on this. I will try to keep you updated.

**Comment by YoloZoloo** [comment]
@VidurK2 I just added all the changed files from the upstream repo. Could you try again now?
If the issue persists, feel free to re-open this issue. I would also appreciate it if you can give any kind of feedback.
